/* MediaSuite Phase 17 — Professional UX System */
(function(){
  const settingsKey='mediasuite_ux_settings_v1';
  const defaults={density:'comfortable',contrast:false,accent:'#00e5ff',fontScale:1,focusMode:false};
  let settings={...defaults,...load()};
  function load(){try{return JSON.parse(localStorage.getItem(settingsKey)||'{}')}catch(e){return {}}}
  function save(){localStorage.setItem(settingsKey,JSON.stringify(settings));apply();}
  function apply(){document.documentElement.style.setProperty('--phase-accent',settings.accent);document.documentElement.style.setProperty('--phase-font-scale',settings.fontScale);document.body.classList.toggle('ms-density-compact',settings.density==='compact');document.body.classList.toggle('ms-high-contrast',!!settings.contrast);document.body.classList.toggle('ms-focus-mode',!!settings.focusMode);}
  const shortcuts={Space:'Play/Pause',ArrowLeft:'Nudge Back',ArrowRight:'Nudge Forward',KeyA:'Load/Focus Deck A',KeyB:'Load/Focus Deck B',KeyF:'Focus Search',KeyR:'Record Toggle',Digit1:'Hot Cue 1',Digit2:'Hot Cue 2',Digit3:'Hot Cue 3',Digit4:'Hot Cue 4'};
  function toast(msg){let el=document.getElementById('msUxToast');if(!el){el=document.createElement('div');el.id='msUxToast';el.className='ms-ux-toast';document.body.appendChild(el)}el.textContent=msg;clearTimeout(el._t);el._t=setTimeout(()=>el.remove(),1800)}
  function keyHandler(e){if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return; if(!shortcuts[e.code])return; e.preventDefault(); const code=e.code; if(code==='KeyF'){document.querySelector('input[type="search"],#coreSearch,.search-input')?.focus();return} if(code==='Space')document.getElementById('btnPlay')?.click(); if(code==='KeyR')window.MediaSuiteRecorder?.toggle?.(); if(/^Digit[1-4]$/.test(code))window.MediaSuiteCues?.trigger?.(Number(code.slice(-1))); toast(shortcuts[code]);}
  function panel(){return `<div class="ux-shell"><h3>Phase 17 — UX System</h3><label>Density <select id="uxDensity"><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label><label>Accent <input id="uxAccent" type="color" value="${settings.accent}"></label><label>Font Scale <input id="uxFont" type="range" min=".85" max="1.25" step=".05" value="${settings.fontScale}"></label><label><input id="uxContrast" type="checkbox" ${settings.contrast?'checked':''}> High Contrast</label><label><input id="uxFocus" type="checkbox" ${settings.focusMode?'checked':''}> Focus Mode</label><details><summary>Keyboard Shortcuts</summary>${Object.entries(shortcuts).map(([k,v])=>`<div><kbd>${k.replace('Key','').replace('Digit','')}</kbd><span>${v}</span></div>`).join('')}</details></div>`}
  function render(){let root=document.getElementById('phase17Panel');if(!root){root=document.createElement('div');root.id='phase17Panel';document.body.appendChild(root)}root.innerHTML=panel();root.querySelector('#uxDensity').value=settings.density;root.querySelector('#uxDensity').onchange=e=>{settings.density=e.target.value;save()};root.querySelector('#uxAccent').oninput=e=>{settings.accent=e.target.value;save()};root.querySelector('#uxFont').oninput=e=>{settings.fontScale=e.target.value;save()};root.querySelector('#uxContrast').onchange=e=>{settings.contrast=e.target.checked;save()};root.querySelector('#uxFocus').onchange=e=>{settings.focusMode=e.target.checked;save()};}
  window.MediaSuiteUX={settings,apply,render};document.addEventListener('keydown',keyHandler);document.addEventListener('DOMContentLoaded',()=>{apply();render();});
})();
